import type { Product } from "./types"

export const featuredProducts: Product[] = [
  {
    id: "1",
    name: "Neon Graphic Tee",
    description: "Bold graphic tee with neon accents",
    price: 49.99,
    salePrice: 39.99,
    onSale: true,
    image: "/placeholder.svg?height=400&width=300",
    category: "Apparel",
    tags: ["tshirt", "graphic", "neon"],
    rating: 4,
    stock: 100,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
  },
  {
    id: "2",
    name: "Urban Tech Hoodie",
    description: "Premium hoodie with futuristic design elements",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Apparel",
    tags: ["hoodie", "tech", "urban"],
    rating: 5,
    stock: 75,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Red"],
  },
  {
    id: "3",
    name: "Cargo Tech Pants",
    description: "Functional cargo pants with multiple pockets",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Apparel",
    tags: ["pants", "cargo", "tech"],
    rating: 4,
    stock: 50,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Black", "Gray"],
  },
  {
    id: "4",
    name: "Digital Camo Jacket",
    description: "Lightweight jacket with digital camo pattern",
    price: 129.99,
    salePrice: 99.99,
    onSale: true,
    image: "/placeholder.svg?height=400&width=300",
    category: "Outerwear",
    tags: ["jacket", "camo", "digital"],
    rating: 5,
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black/Red", "Black/White"],
  },
  {
    id: "5",
    name: "Reflective Sneakers",
    description: "High-top sneakers with reflective details",
    price: 119.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Footwear",
    tags: ["sneakers", "reflective", "high-top"],
    rating: 4,
    stock: 30,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White/Red"],
  },
  {
    id: "6",
    name: "Tech Backpack",
    description: "Water-resistant backpack with multiple compartments",
    price: 69.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Accessories",
    tags: ["backpack", "tech", "water-resistant"],
    rating: 5,
    stock: 60,
    sizes: ["One Size"],
    colors: ["Black", "Black/Red"],
  },
  {
    id: "7",
    name: "Wireless Earbuds",
    description: "Premium wireless earbuds with charging case",
    price: 149.99,
    salePrice: 129.99,
    onSale: true,
    image: "/placeholder.svg?height=400&width=300",
    category: "Electronics",
    tags: ["earbuds", "wireless", "audio"],
    rating: 4,
    stock: 25,
    sizes: ["One Size"],
    colors: ["Black", "White"],
  },
  {
    id: "8",
    name: "Logo Cap",
    description: "Adjustable cap with embroidered logo",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "Accessories",
    tags: ["cap", "hat", "logo"],
    rating: 4,
    stock: 80,
    sizes: ["One Size"],
    colors: ["Black", "Red", "White"],
  },
]

